version: "3.7"
services:
  floatha:
    image: ghcr.io/lovelysystems/floatha:dev
    volumes:
      # mount the local doctl config file to the container for local testing
      # in a swarm you would probably create a secret for this
      - $HOME/.config/doctl/config.yaml:/root/.config/doctl/config.yaml
    environment:
      FLOATING_HEALTH_URI: "http://1.1.1.1:8080/ping"
      DROPLET_TAG: "traefik"
      CHECK_WAIT_TIME: "1000"
      RETRY_WAIT_TIME: "1000"
      NUM_RETRIES: "5"
